import PageHeader from '@/layouts/PageHeader';
import { useImages } from '@/context/useImages';

const companyName = import.meta.env.VITE_COMPANY_NAME || 'Florence Walters Consulting';
const companyEmail = import.meta.env.VITE_COMPANY_EMAIL || 'info@florencewaltersconsulting.com';

function Terms() {
	const images = useImages();
	return (
		<div className="page-enter">
			<PageHeader title="Terms of Service" heading="Clear terms for using our website" text="These terms govern your access to this website and the information and services made available through it." image={images['Terms Header']} />
			<section className="legal-page">
				<div className="legal-page-intro"><p>Last updated: 11 July 2026</p><h2>Website Terms of Service</h2><p>Please read these terms carefully before using this website. By accessing or using it, you agree to these terms. If you do not agree, please discontinue your use of the website.</p></div>
				<div className="legal-page-layout">
					<nav className="legal-page-nav" aria-label="Terms of service sections"><span>On this page</span><a href="#website-use">Using the website</a><a href="#advisory">Advisory services</a><a href="#content">Website content</a><a href="#intellectual-property">Intellectual property</a><a href="#liability">Liability</a><a href="#governing-law">Governing law</a><a href="#terms-contact">Contact us</a></nav>
					<div className="legal-page-content">
						<section><h2>1. About these terms</h2><p>This website is operated by {companyName}, a business and regulatory advisory firm in Nigeria. References to “we”, “us”, or “our” mean {companyName}. References to “you” mean any person accessing or using this website.</p><p>These terms apply to the public website, its articles and resources, consultation and contact forms, newsletter subscription, and any other website feature that links to these terms. A separate engagement letter or service agreement will govern any professional services we agree to provide.</p></section>
						<section id="website-use"><h2>2. Acceptable use</h2><p>You may use this website for lawful personal or business purposes. You agree that you will not:</p><ul><li>Use the website in a way that violates any applicable law or infringes another person’s rights.</li><li>Attempt to gain unauthorised access to the website, its server, accounts, databases, or connected systems.</li><li>Introduce malicious code, interfere with security controls, overload the website, or disrupt its operation.</li><li>Use automated tools to scrape, harvest, copy, or extract website content or personal information without our written permission.</li><li>Submit false, misleading, unlawful, abusive, or unsolicited promotional material through our forms.</li><li>Misrepresent your identity, affiliation, authority, or purpose when communicating with us.</li></ul><p>We may restrict or block access where we reasonably believe these terms have been breached or the website’s security or availability is at risk.</p></section>
						<section id="advisory"><h2>3. Enquiries and advisory services</h2><p>Submitting a contact form, booking request, email, or other enquiry does not by itself create a client, adviser, fiduciary, or confidential professional relationship between you and us. An advisory engagement begins only after we have accepted the engagement and the parties have agreed the applicable scope, fees, responsibilities, and other terms in writing.</p><p>Please do not treat an acknowledgement or preliminary response as confirmation that we have accepted an engagement. Until an engagement is confirmed, you remain responsible for protecting deadlines, obtaining advice, and taking any action needed in relation to your matter.</p><p>Information you submit must be accurate and complete to the best of your knowledge. Our ability to assess or provide services may depend on the quality and timeliness of information supplied by you.</p></section>
						<section id="content"><h2>4. Information, articles, and resources</h2><p>Website content is provided for general information and educational purposes. It does not constitute legal, tax, accounting, investment, financial, regulatory, or other professional advice and should not be relied upon as a substitute for advice tailored to your circumstances.</p><p>Laws, regulations, official practices, market conditions, and other information may change after content is published. Although we aim to provide useful and accurate material, we do not guarantee that every item is complete, current, error-free, or suitable for a particular purpose. You should obtain appropriate professional advice before making a decision or taking action based on website content.</p></section>
						<section><h2>5. Newsletter and communications</h2><p>If you subscribe to our newsletter, you consent to receive insights, news, and service updates at the email address provided. You may unsubscribe at any time using an unsubscribe method included in a message or by contacting us. Administrative messages relating to an active enquiry or engagement are not marketing communications.</p><p>Electronic communications may be delayed, intercepted, corrupted, or contain malicious material. You are responsible for using appropriate security measures when communicating electronically.</p></section>
						<section id="intellectual-property"><h2>6. Intellectual property</h2><p>Unless otherwise stated, the website and its design, branding, text, graphics, articles, documents, downloads, and other original material are owned by or licensed to {companyName} and are protected by applicable intellectual-property laws.</p><p>You may view, download, or print reasonable extracts for your own internal, non-commercial use, provided you do not alter the material or remove ownership notices. You may link to publicly available pages in a fair and lawful manner that does not imply an endorsement or association.</p><p>You may not reproduce, republish, sell, license, distribute, modify, create derivative works from, or commercially exploit a substantial part of the website without our prior written permission.</p></section>
						<section><h2>7. Third-party services and links</h2><p>The website may include links to external websites or use third-party services such as Google reCAPTCHA. These services are controlled by their respective providers and may be subject to separate terms and privacy policies. Links are supplied for convenience and do not necessarily mean that we endorse or control the linked content.</p><p>We are not responsible for the availability, security, accuracy, or practices of third-party websites or services. You access them at your own discretion.</p></section>
						<section><h2>8. Website availability and changes</h2><p>We may update, suspend, restrict, or withdraw any part of the website without notice. We do not guarantee that the website will always be available, uninterrupted, secure, or free from defects. You are responsible for maintaining the devices, software, connectivity, and security needed to access it.</p><p>We may revise these terms when our services, website, or legal obligations change. The revised terms take effect when posted unless a different effective date is stated.</p></section>
						<section id="liability"><h2>9. Disclaimers and limitation of liability</h2><p>To the fullest extent permitted by law, the website and its content are provided on an “as available” basis without warranties or representations, whether express or implied, regarding availability, accuracy, fitness for a particular purpose, or non-infringement.</p><p>To the fullest extent permitted by law, we will not be liable for indirect, incidental, special, punitive, or consequential loss arising from use of, inability to use, or reliance on this website, including loss of profits, revenue, opportunity, goodwill, data, or anticipated savings.</p><p>Nothing in these terms excludes or limits liability where doing so would be unlawful, including liability that cannot be excluded under applicable law. Any liability arising from separately contracted professional services will be governed by the relevant engagement agreement.</p></section>
						<section><h2>10. Privacy</h2><p>Our <a href="/privacy">Privacy Policy</a> explains how we collect and process personal information through this website. Our <a href="/cookies">Cookie Policy</a> provides further information about cookies and similar technologies. These policies form part of the framework governing your use of the website.</p></section>
						<section><h2>11. Severability and waiver</h2><p>If any provision of these terms is found to be unlawful, invalid, or unenforceable, that provision will be treated as modified to the minimum extent necessary or removed, while the remaining provisions continue in effect. A delay or failure to enforce a provision does not waive our right to enforce it later.</p></section>
						<section id="governing-law"><h2>12. Governing law and disputes</h2><p>These website terms are governed by the laws of the Federal Republic of Nigeria. We encourage you to contact us first so that any concern can be addressed promptly and in good faith. If a dispute cannot be resolved informally, it will be subject to the jurisdiction of the competent courts in Nigeria, unless applicable law requires otherwise.</p></section>
						<section id="terms-contact"><h2>13. Contact us</h2><p>Questions about these terms may be sent to:</p><address><strong>{companyName}</strong><br />17a Rasaq Gbadamosi Avenue<br />Surulere, Lagos, Nigeria<br /><a href={`mailto:${companyEmail}`}>{companyEmail}</a></address></section>
					</div>
				</div>
			</section>
		</div>
	);
}

export default Terms;
